### ISSUE TITLE
license

### ISSUE THREAD

**Issue by mand35** [pletzer/scatter#6]
Since I am just reading about it: It would be useful, when you could add a license statement.

**Comment by mand35** [comment]
Furthermore, of minor interest, but nice to have, a citation file, you could at least include BibTex @software{... statement (see https://swcarpentry.github.io/git-novice/12-citation/index.html) 

Links for licenses can also be found at https://swcarpentry.github.io/git-novice/11-licensing/index.html

**Comment by pletzer** [comment]
Thanks @mand35. I added LICENSE.txt, CITATION.txt and VERSION.txt
